"""
Unit tests for Phase 2 crypt4gh support: staging, mock re-encryptor service,
and the prepare_crypt4gh_input utility.

Key files used by these tests:

    test-data/crypt4gh/user_key.sec    — user private key (Crypt4GH format)
    test-data/crypt4gh/user_key.pub    — user public key
    test-data/crypt4gh/compute_key.sec — compute private key
    test-data/crypt4gh/compute_key.pub — compute public key
    test-data/crypt4gh/test.fastqsanger.crypt4gh — encrypted with user_key.pub

These files are generated by the Phase 2 test fixture setup in conftest.py and
committed to the repository for reproducible test runs.
"""

import base64
import io
import os
import sys
from pathlib import Path
from unittest.mock import MagicMock

import crypt4gh.header
import crypt4gh.lib
import pytest
import requests
from crypt4gh.keys import get_private_key

from galaxy.jobs.crypt4gh_staging import (
    build_crypt4gh_output_post_commands,
    build_crypt4gh_post_commands,
    build_crypt4gh_pre_commands,
    fetch_user_public_key,
    JobPreparationException,
    plan_crypt4gh_output_staging,
    prepare_crypt4gh_input,
    StagedCrypt4GHInput,
    StagedCrypt4GHOutput,
)

# ---------------------------------------------------------------------------
# Resolve paths relative to the workspace root
# ---------------------------------------------------------------------------

_WORKSPACE_ROOT = Path(__file__).parents[3]  # test/unit/jobs/ → repo root
_C4GH_TEST_DIR = _WORKSPACE_ROOT / "test-data" / "crypt4gh"
_USER_SEC = str(_C4GH_TEST_DIR / "user_key.sec")
_USER_PUB = str(_C4GH_TEST_DIR / "user_key.pub")
_COMPUTE_SEC = str(_C4GH_TEST_DIR / "compute_key.sec")
_COMPUTE_PUB = str(_C4GH_TEST_DIR / "compute_key.pub")
_TEST_C4GH_FILE = str(_C4GH_TEST_DIR / "test.fastqsanger.crypt4gh")

# Add test/unit/jobs/ to sys.path so mock_recryptor_service can be imported as
# a plain module (test/ has no __init__.py, so the dotted path is unavailable).
sys.path.insert(0, str(Path(__file__).parent))
from mock_recryptor_service import MockRecryptorServer  # noqa: E402

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture(scope="session")
def mock_recryptor():
    """Session-scoped fixture: start the mock re-encryptor service once."""
    srv = MockRecryptorServer(
        user_private_key_path=_USER_SEC,
        compute_public_key_path=_COMPUTE_PUB,
        user_public_key_path=_USER_PUB,
    )
    srv.start()
    yield srv
    srv.stop()


@pytest.fixture
def crypt4gh_test_dataset():
    """Return a minimal mock dataset that mimics a real crypt4gh HDA."""
    # Read the stored header from the test file
    with open(_TEST_C4GH_FILE, "rb") as f:
        content = f.read()

    stream = io.BytesIO(content)
    list(crypt4gh.header.parse(stream))
    header_end = stream.tell()
    header_bytes = content[:header_end]
    header_b64 = base64.b64encode(header_bytes).decode("ascii")

    mock_metadata = MagicMock()
    mock_metadata.crypt4gh_header = header_b64

    mock_dataset = MagicMock()
    mock_dataset.id = 42
    mock_dataset.metadata = mock_metadata
    mock_dataset.get_file_name.return_value = _TEST_C4GH_FILE
    mock_dataset.datatype = MagicMock()
    mock_dataset.datatype.compressed_format = "crypt4gh"

    return mock_dataset


# ---------------------------------------------------------------------------
# Tests: mock_recryptor_service.py
# ---------------------------------------------------------------------------


class TestMockRecryptorService:
    """Verify that the mock service correctly re-encrypts headers and complies
    with the real service API contract."""

    def test_info_endpoint(self, mock_recryptor):
        """GET /info should return service metadata."""
        response = requests.get(f"{mock_recryptor.url}/info", timeout=5)
        assert response.status_code == 200
        data = response.json()
        assert data["name"] == "mock-crypt4gh-recryptor"

    def test_recrypt_header_returns_valid_response(self, mock_recryptor, crypt4gh_test_dataset):
        """POST /recrypt_header should return all required fields."""
        header_b64 = crypt4gh_test_dataset.metadata.crypt4gh_header
        response = requests.post(
            f"{mock_recryptor.url}/recrypt_header",
            json={"crypt4gh_header": header_b64},
            timeout=10,
        )
        assert response.status_code == 200, response.text
        data = response.json()
        # Check all required fields are present (matches UserRecryptResponse schema)
        assert "crypt4gh_header" in data
        assert "crypt4gh_compute_keypair_id" in data
        assert "crypt4gh_compute_keypair_expiration_date" in data

    def test_recrypt_header_produces_valid_crypt4gh_header(self, mock_recryptor, crypt4gh_test_dataset):
        """The returned re-encrypted header must start with the crypt4gh magic."""
        header_b64 = crypt4gh_test_dataset.metadata.crypt4gh_header
        response = requests.post(
            f"{mock_recryptor.url}/recrypt_header",
            json={"crypt4gh_header": header_b64},
            timeout=10,
        )
        assert response.status_code == 200
        new_header_bytes = base64.b64decode(response.json()["crypt4gh_header"])
        assert new_header_bytes.startswith(b"crypt4gh"), "Re-encrypted header must start with crypt4gh magic bytes"
        # Must be parse-able as a crypt4gh header
        stream = io.BytesIO(new_header_bytes)
        packets = list(crypt4gh.header.parse(stream))
        assert len(packets) >= 1

    def test_recrypt_header_compute_keypair_id_is_stable(self, mock_recryptor, crypt4gh_test_dataset):
        """The mock always returns the same compute keypair ID."""
        header_b64 = crypt4gh_test_dataset.metadata.crypt4gh_header
        response = requests.post(
            f"{mock_recryptor.url}/recrypt_header",
            json={"crypt4gh_header": header_b64},
            timeout=10,
        )
        assert response.json()["crypt4gh_compute_keypair_id"] == "mock-compute-key-1"

    def test_recrypt_header_bad_request_returns_400(self, mock_recryptor):
        """Non-crypt4gh payload should return HTTP 400."""
        not_a_header = base64.b64encode(b"this is not a crypt4gh header").decode("ascii")
        response = requests.post(
            f"{mock_recryptor.url}/recrypt_header",
            json={"crypt4gh_header": not_a_header},
            timeout=10,
        )
        assert response.status_code == 400

    def test_user_public_key_endpoint_returns_key(self, mock_recryptor):
        response = requests.get(
            f"{mock_recryptor.url}/user_public_key",
            params={"user_id": "user@test.invalid"},
            timeout=5,
        )
        assert response.status_code == 200
        key_b64 = response.json()["crypt4gh_public_key"]
        key_bytes = base64.b64decode(key_b64)
        assert len(key_bytes) == 32

    def test_user_public_key_endpoint_requires_user_id(self, mock_recryptor):
        response = requests.get(f"{mock_recryptor.url}/user_public_key", timeout=5)
        assert response.status_code == 422


# ---------------------------------------------------------------------------
# Tests: prepare_crypt4gh_input
# ---------------------------------------------------------------------------


class TestPrepareCrypt4GHInput:
    """Verify the crypt4gh_staging.prepare_crypt4gh_input function."""

    def test_staged_file_starts_with_crypt4gh_magic(self, mock_recryptor, crypt4gh_test_dataset, tmp_path):
        """The staged file must start with the crypt4gh magic bytes."""
        result = prepare_crypt4gh_input(
            dataset=crypt4gh_test_dataset,
            reencryption_service_url=mock_recryptor.url,
            working_directory=str(tmp_path),
            compute_key_path=_COMPUTE_SEC,
        )
        with open(result.staged_path, "rb") as f:
            assert f.read(8) == b"crypt4gh", "Staged file must start with crypt4gh magic"

    def test_staged_file_is_decryptable_with_compute_key(self, mock_recryptor, crypt4gh_test_dataset, tmp_path):
        """The staged file's body (original encrypted content) must remain intact
        and the new header must be decryptable with the compute private key."""
        result = prepare_crypt4gh_input(
            dataset=crypt4gh_test_dataset,
            reencryption_service_url=mock_recryptor.url,
            working_directory=str(tmp_path),
            compute_key_path=_COMPUTE_SEC,
        )
        compute_sk = get_private_key(_COMPUTE_SEC, lambda: b"")
        with open(result.staged_path, "rb") as infile:
            outstream = io.BytesIO()
            crypt4gh.lib.decrypt([(0, compute_sk, None)], infile, outstream)
        decrypted = outstream.getvalue()
        # The original plaintext was a small FASTQ snippet
        assert decrypted != b"", "Decryption must yield non-empty content"
        assert b"@read" in decrypted or decrypted  # just verify it decrypted OK

    def test_staged_file_body_equals_original_body(self, mock_recryptor, crypt4gh_test_dataset, tmp_path):
        """The encrypted body in the staged file must be byte-for-byte identical
        to the original (only the header is replaced)."""
        result = prepare_crypt4gh_input(
            dataset=crypt4gh_test_dataset,
            reencryption_service_url=mock_recryptor.url,
            working_directory=str(tmp_path),
            compute_key_path=_COMPUTE_SEC,
        )

        with open(result.staged_path, "rb") as f:
            staged_content = f.read()

        # Find header boundary in staged file
        staged_stream = io.BytesIO(staged_content)
        list(crypt4gh.header.parse(staged_stream))
        staged_header_end = staged_stream.tell()
        staged_body = staged_content[staged_header_end:]

        # Find header boundary in original file
        with open(_TEST_C4GH_FILE, "rb") as f:
            original_content = f.read()
        orig_stream = io.BytesIO(original_content)
        list(crypt4gh.header.parse(orig_stream))
        orig_header_end = orig_stream.tell()
        original_body = original_content[orig_header_end:]

        assert staged_body == original_body, "Re-staged file body must be identical to the original encrypted body"

    def test_decrypted_path_field_is_inside_stage_dir(self, mock_recryptor, crypt4gh_test_dataset, tmp_path):
        """decrypted_path must be a child of stage_dir."""
        result = prepare_crypt4gh_input(
            dataset=crypt4gh_test_dataset,
            reencryption_service_url=mock_recryptor.url,
            working_directory=str(tmp_path),
            compute_key_path=_COMPUTE_SEC,
        )
        assert result.decrypted_path.startswith(result.stage_dir + os.sep)

    def test_prepare_fails_without_metadata(self, mock_recryptor, tmp_path):
        """prepare_crypt4gh_input must raise if crypt4gh_header metadata is missing."""
        mock_metadata = MagicMock()
        mock_metadata.crypt4gh_header = None
        mock_dataset = MagicMock()
        mock_dataset.id = 99
        mock_dataset.metadata = mock_metadata
        mock_dataset.get_file_name.return_value = _TEST_C4GH_FILE

        with pytest.raises(JobPreparationException, match="missing crypt4gh_header metadata"):
            prepare_crypt4gh_input(
                dataset=mock_dataset,
                reencryption_service_url=mock_recryptor.url,
                working_directory=str(tmp_path),
                compute_key_path=_COMPUTE_SEC,
            )

    def test_prepare_fails_on_missing_key_path(self, mock_recryptor, crypt4gh_test_dataset, tmp_path):
        """prepare_crypt4gh_input must raise if compute_key_path is empty."""
        with pytest.raises(JobPreparationException, match="compute_key_path is required"):
            prepare_crypt4gh_input(
                dataset=crypt4gh_test_dataset,
                reencryption_service_url=mock_recryptor.url,
                working_directory=str(tmp_path),
                compute_key_path="",
            )

    def test_prepare_fails_on_nonexistent_key_path(self, mock_recryptor, crypt4gh_test_dataset, tmp_path):
        """prepare_crypt4gh_input must raise if compute_key_path does not exist."""
        with pytest.raises(JobPreparationException, match="not found"):
            prepare_crypt4gh_input(
                dataset=crypt4gh_test_dataset,
                reencryption_service_url=mock_recryptor.url,
                working_directory=str(tmp_path),
                compute_key_path="/nonexistent/path/key.sec",
            )

    def test_prepare_fails_on_service_error(self, crypt4gh_test_dataset, tmp_path):
        """prepare_crypt4gh_input must raise if the re-encryptor service is unreachable."""
        with pytest.raises(JobPreparationException, match="Failed to contact"):
            prepare_crypt4gh_input(
                dataset=crypt4gh_test_dataset,
                reencryption_service_url="http://127.0.0.1:1",  # No server here
                working_directory=str(tmp_path),
                compute_key_path=_COMPUTE_SEC,
            )

    def test_staged_directories_and_file_created(self, mock_recryptor, crypt4gh_test_dataset, tmp_path):
        """stage_dir must be created and staged_path must exist; no conf file is written."""
        result = prepare_crypt4gh_input(
            dataset=crypt4gh_test_dataset,
            reencryption_service_url=mock_recryptor.url,
            working_directory=str(tmp_path),
            compute_key_path=_COMPUTE_SEC,
        )
        assert os.path.isdir(result.stage_dir)
        assert os.path.isfile(result.staged_path)
        # No crypt4ghfs conf file should be written
        conf_files = list(Path(result.stage_dir).glob("*.conf"))
        assert conf_files == [], "No crypt4ghfs conf files should be written"


class TestFetchUserPublicKey:
    def test_fetch_user_public_key_returns_bytes(self, mock_recryptor):
        key = fetch_user_public_key("user@test.invalid", mock_recryptor.url)
        assert len(key) == 32

    def test_fetch_user_public_key_propagates_service_error(self):
        with pytest.raises(JobPreparationException, match="Failed to contact"):
            fetch_user_public_key("user@test.invalid", "http://127.0.0.1:1")


# ---------------------------------------------------------------------------
# Tests: build_crypt4gh_pre_commands / build_crypt4gh_post_commands
# ---------------------------------------------------------------------------


class TestBuildCommands:
    """Verify the shell snippet generators produce correct shell syntax."""

    def _make_staged_input(self, idx: int) -> "StagedCrypt4GHInput":
        return StagedCrypt4GHInput(
            staged_path=f"/wd/_c4gh_stage/ds_{idx}/input.crypt4gh",
            stage_dir=f"/wd/_c4gh_stage/ds_{idx}",
            decrypted_path=f"/wd/_c4gh_stage/ds_{idx}/input",
            original_dataset_path=f"/galaxy/files/dataset_{idx}.dat",
            compute_keypair_id="mock-compute-key-1",
        )

    def _make_staged_output(self, idx: int) -> "StagedCrypt4GHOutput":
        return StagedCrypt4GHOutput(
            dataset_id=idx,
            plaintext_path=f"/wd/outputs/dataset_{idx}.dat",
            encrypted_marker_path=f"/wd/_c4gh_stage/outputs/ds_{idx}.encrypted",
            encrypted_ext="fastqsanger.crypt4gh",
        )

    def test_pre_commands_invoke_python_decrypt(self):
        si = self._make_staged_input(0)
        cmds = build_crypt4gh_pre_commands([si], compute_key_path="/path/compute.sec")
        assert "${GALAXY_VIRTUAL_ENV}/bin/python" in cmds
        assert "crypt4gh.lib.decrypt" in cmds
        assert si.staged_path in cmds
        assert si.decrypted_path in cmds
        # No crypt4ghfs or fusermount references
        assert "crypt4ghfs" not in cmds
        assert "fusermount" not in cmds

    def test_pre_commands_contain_fail_fast_guard(self):
        si = self._make_staged_input(0)
        cmds = build_crypt4gh_pre_commands([si], compute_key_path="/path/compute.sec")
        assert "exit 1" in cmds
        assert si.decrypted_path in cmds

    def test_post_commands_remove_decrypted_file(self):
        si = self._make_staged_input(0)
        cmds = build_crypt4gh_post_commands([si])
        assert "rm -f" in cmds
        assert si.decrypted_path in cmds
        # No fusermount or PID tracking
        assert "fusermount" not in cmds
        assert "_CRYPT4GHFS_PID" not in cmds

    def test_passphrase_env_injected_when_provided(self):
        si = self._make_staged_input(0)
        cmds = build_crypt4gh_pre_commands([si], compute_key_path="/path/compute.sec", passphrase_env="MY_C4GH_PASS")
        assert "MY_C4GH_PASS" in cmds

    def test_no_passphrase_env_uses_empty_bytes(self):
        si = self._make_staged_input(0)
        cmds = build_crypt4gh_pre_commands([si], compute_key_path="/path/compute.sec", passphrase_env=None)
        assert 'b""' in cmds
        assert "MY_C4GH_PASS" not in cmds

    def test_multiple_inputs_generate_multiple_decrypt_blocks(self):
        inputs = [self._make_staged_input(i) for i in range(3)]
        pre = build_crypt4gh_pre_commands(inputs, compute_key_path="/path/compute.sec")
        post = build_crypt4gh_post_commands(inputs)
        # Each input's paths must appear in the respective snippet
        for si in inputs:
            assert si.staged_path in pre
            assert si.decrypted_path in pre
            assert si.decrypted_path in post

    def test_output_post_commands_invoke_encrypt_and_marker(self):
        so = self._make_staged_output(7)
        cmds = build_crypt4gh_output_post_commands([so], user_public_key=b"a" * 32)
        assert "crypt4gh.lib.encrypt" in cmds
        assert so.plaintext_path in cmds
        assert so.encrypted_marker_path in cmds
        assert "return_code=1" in cmds

    def test_output_post_commands_empty_returns_empty(self):
        assert build_crypt4gh_output_post_commands([], user_public_key=b"a" * 32) == ""


class TestPlanCrypt4GHOutputStaging:
    def _mock_output_dataset(self, ext: str, dataset_id: int = 7):
        dataset = MagicMock()
        dataset.ext = ext
        dataset.dataset = MagicMock()
        dataset.dataset.id = dataset_id
        return dataset

    def _mock_dataset_path(self, path: str = "/wd/output.dat"):
        dataset_path = MagicMock()
        dataset_path.false_path = path
        return dataset_path

    def test_plan_output_staging_returns_eligible_output(self, tmp_path):
        output_hdas_and_paths = {
            "out1": (
                self._mock_output_dataset("fastqsanger", dataset_id=42),
                self._mock_dataset_path("/wd/out1.dat"),
            )
        }
        tool_outputs: dict[str, object] = {}
        datatypes_registry = MagicMock()
        datatypes_registry.get_datatype_by_extension.return_value = object()

        staged_outputs = plan_crypt4gh_output_staging(
            output_hdas_and_paths=output_hdas_and_paths,
            tool_outputs=tool_outputs,
            datatypes_registry=datatypes_registry,
            working_directory=str(tmp_path),
            outputs_to_working_directory=True,
        )

        assert len(staged_outputs) == 1
        staged = staged_outputs[0]
        assert staged.dataset_id == 42
        assert staged.plaintext_path == "/wd/out1.dat"
        assert staged.encrypted_ext == "fastqsanger.crypt4gh"
        assert staged.encrypted_marker_path.endswith("_c4gh_stage/outputs/ds_42.encrypted")

    def test_plan_output_staging_raises_without_outputs_to_working_directory(self, tmp_path):
        output_hdas_and_paths = {
            "out1": (
                self._mock_output_dataset("fastqsanger", dataset_id=42),
                self._mock_dataset_path("/wd/out1.dat"),
            )
        }
        datatypes_registry = MagicMock()
        datatypes_registry.get_datatype_by_extension.return_value = object()

        with pytest.raises(JobPreparationException, match="outputs_to_working_directory=true"):
            plan_crypt4gh_output_staging(
                output_hdas_and_paths=output_hdas_and_paths,
                tool_outputs={},
                datatypes_registry=datatypes_registry,
                working_directory=str(tmp_path),
                outputs_to_working_directory=False,
            )
